<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Reportes - Valle de San Remo</title><link rel="stylesheet" href="{{ asset('estilos.css') }}"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></head>
<body><div class="layout-principal">@include('partials.navegacion')<main class="zona-trabajo">
<div class="encabezado-seccion"><h2>Reportes de Paquetería</h2><p>Consulta el flujo y custodia de paquetes del conjunto.</p></div><div class="contenedor-tabla">
<form class="filtros-historial" method="get" action="{{ route('reportes') }}">
<div class="filtro-grupo"><label for="fecha_desde">Fecha desde</label><input class="filtro-fecha" type="date" id="fecha_desde" name="fecha_desde" value="{{ $filtros['fecha_desde'] ?? '' }}"></div><div class="filtro-grupo"><label for="fecha_hasta">Fecha hasta</label><input class="filtro-fecha" type="date" id="fecha_hasta" name="fecha_hasta" value="{{ $filtros['fecha_hasta'] ?? '' }}"></div><div class="filtro-grupo"><label for="estado">Estado</label><select class="filtro-select" id="estado" name="estado"><option value="Todos" @selected($filtros['estado'] === 'Todos')>Todos</option><option value="Pendiente" @selected($filtros['estado'] === 'Pendiente')>Pendiente</option><option value="Entregado" @selected($filtros['estado'] === 'Entregado')>Entregado</option></select></div><div class="filtro-grupo"><label for="torre">Torre</label><input class="filtro-fecha" type="text" id="torre" name="torre" value="{{ $filtros['torre'] ?? '' }}"></div><div class="filtro-grupo"><label for="apartamento">Apartamento</label><input class="filtro-fecha" type="text" id="apartamento" name="apartamento" value="{{ $filtros['apartamento'] ?? '' }}"></div><div class="filtro-grupo"><label for="residente">Residente</label><input class="filtro-fecha" type="text" id="residente" name="residente" value="{{ $filtros['residente'] ?? '' }}"></div><div class="filtro-grupo"><label for="dias_custodia">Días en custodia</label><input class="filtro-fecha" type="number" min="1" id="dias_custodia" name="dias_custodia" value="{{ $filtros['dias_custodia'] }}"></div><div class="filtro-grupo filtros-acciones"><label>&nbsp;</label><div class="filtros-botones"><button type="submit" class="btn-confirmar-verde btn-buscar"><i class="fas fa-search"></i> Buscar</button><a href="{{ route('reportes') }}" class="btn-limpiar-filtros">Limpiar</a></div></div>
</form>
@if ($errors->any())<div class="alerta-error">{{ $errors->first() }}</div>@endif
<div class="dashboard-grid-cards" style="margin: 20px 0;"><div class="card-resumen"><span>Total recibidos</span><strong>{{ $total }}</strong></div><div class="card-resumen"><span>Pendientes</span><strong>{{ $pendientes }}</strong></div><div class="card-resumen"><span>Entregados</span><strong>{{ $entregados }}</strong></div><div class="card-resumen"><span>Promedio de retiro</span><strong>{{ $promedioHoras === null ? 'Sin datos' : number_format($promedioHoras, 1, ',', '.') . ' horas' }}</strong></div><div class="card-resumen"><span>Custodia &gt; {{ $filtros['dias_custodia'] }} días</span><strong>{{ $enCustodia }}</strong></div></div>
<div class="filtros-botones" style="justify-content: flex-end; margin-bottom: 16px;"><a class="btn-confirmar-verde btn-buscar" href="{{ route('reportes.exportar', request()->except('page')) }}"><i class="fas fa-file-csv"></i> Exportar CSV</a></div>
<table class="tabla-datos"><thead><tr><th>Recepción</th><th>Guía</th><th>Empresa</th><th>Residente</th><th>Torre</th><th>Apartamento</th><th>Estado</th><th>Entrega</th><th>Recibido por</th><th>Tiempo de retiro</th><th>Días en custodia</th></tr></thead><tbody>@forelse ($paquetes as $paquete)<tr><td>{{ $paquete->created_at?->format('d/m/Y H:i') ?? '-' }}</td><td>{{ $paquete->guia ?? '-' }}</td><td>{{ $paquete->empresa ?? '-' }}</td><td>{{ $paquete->residente?->nombre ?? '-' }}</td><td>{{ $paquete->apartamento?->torre ?? '-' }}</td><td>{{ $paquete->apartamento?->numero ?? '-' }}</td><td><span class="badge {{ strtolower($paquete->estado) }}">{{ $paquete->estado }}</span></td><td>{{ $paquete->fecha_entrega?->format('d/m/Y H:i') ?? '-' }}</td><td>{{ $paquete->recibido_por ?? '-' }}</td><td>{{ $paquete->estado === 'Entregado' && $paquete->fecha_entrega ? number_format($paquete->created_at->diffInMinutes($paquete->fecha_entrega) / 60, 1, ',', '.') . ' horas' : 'Pendiente' }}</td><td>{{ $paquete->estado === 'Pendiente' ? $paquete->created_at->diffInDays(now()) : '-' }}</td></tr>@empty<tr><td colspan="11">No hay paquetes que coincidan con los filtros seleccionados.</td></tr>@endforelse</tbody></table>
@if ($paquetes->hasPages())<div class="filtros-botones" style="padding: 20px; justify-content: center;">@if ($paquetes->previousPageUrl())<a href="{{ $paquetes->previousPageUrl() }}" class="btn-limpiar-filtros">Anterior</a>@endif<span>Página {{ $paquetes->currentPage() }} de {{ $paquetes->lastPage() }}</span>@if ($paquetes->nextPageUrl())<a href="{{ $paquetes->nextPageUrl() }}" class="btn-confirmar-verde btn-buscar" style="width: auto;">Siguiente</a>@endif</div>@endif
</div></main></div></body></html>
